title: 법철학 번역자료
description: 철학 법철학 번역자료 홈페이지
theme: just-the-docs
baseurl: "/Documents"

url: https://DeepWrite.github.io/

aux_links:
  Hart Concept: https://DeepWrite.github.io/HartConcept 

just_the_docs:
  aux_links:
  toc:
    max_level: 4  # H1=1, H2=2, ..., H4=4